### ISSUE TITLE
Android Auto support

### ISSUE THREAD

**Issue by Sypers** [Team-xManager/xManager#337]
### Description of the new feature / enhancement

Device: Android 13 Stock, xManager 4.9
For some reason the modified spotify version does not work on android auto While the stock spotify app works. It's inconvenient and the added support will be much appreciated 👍.

**Comment by xC3FFF0E** [comment]
Should be supported. Please read the FAQ.

Also, GitHub issues for xManager should be used for the xManager app only.
Any and all issues, requests, and discussions outside the scope of the xManager repo should be moved to the telegram or discord support channels.

xManager Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport

**Comment by Xitee1** [comment]
You need to enable the Android Auto specific developer settings and enable unknown sources (these dev settings are separate from the normal dev settings in Android. They are within the AA App).

However in my case with this solution it did not always work. Sometimes I had to re-plug my phone to the car in order to see the app.
Now I've tried a different way (that is not mentioned anywhere else):
You need to have USB Debugging enabled and have ADB installed on your computer.
When installing the App with xManager, click cancel once the Android packet installer comes up. Navigate to `Android/data/com.xc3fff0e.xmanager/files/Download` and copy the modified APK to your computer.
Plug your phone into your computer and type `adb devices` to verify that your phone is connected.
Type the command `adb install -i "com.android.vending" -r .\path\to\Patched.apk` to install Spotify. The path needs to be on your PC, not your phone. It will install the app and pretend that it has been installed from Google Play. You can open the App details of Spotify in settings and scroll to the bottom. Now it should say something like "Installed from Google Play Store" even tough you manually installed it as APK. Now it will show up in Android Auto without having AA dev settings enabled.
You do not need to uninstall the App for this. The `-r` parameter when installing means to keep all App data (so it only updates the app).

With that, I no longer had the problem that Spotify is sometimes missing in AA. It now works each time I plug my phone into my car.
