### ISSUE TITLE
Google Play Store Does Not recognize this as Spotify.

### ISSUE THREAD

**Issue by Hit4man47** [Team-xManager/xManager#350]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Samsung M51 
- Android Version:  12
- ROM Version:  stock
- xManager Version:  5.0
```

### 📝 Description

1. The Google Play does not recognize it as Spotify.
2. The Google Assistant does not recognize it as Spotify.
3. All links open On the Default browser.
4. Help Urgent.....
...

### 📸 Screenshots

.

**Comment by lokillo-0** [comment]
Well, it's a mod app, idk what you expected since technically it's not the spotify app

**Comment by HJFallen** [comment]
I'm not sure how to resolve the other issues but if you go to Settings -> default apps -> opening links you should be able to make the modded Spotify app open Spotify links.

**Comment by Hit4man47** [comment]
@lokillo-0 bro every other mod is at least recognised by Google Play and is supported by all Devices i.e. echo, Alexa.

**Comment by GitStudying** [comment]
I am confused, for me at least, in the play store it does recognize it and manually offers to update which you shouldn't do by the way. Maybe the reason is an experimental feature. I have it enabled but disabled cloned version, I assume it defaults to true to prevent compatibility issues for people who already have the official version installed.

Try that and see if that words. For the other problem, as said setting it as default manually should get you a long way, it should look like this ![Screenshot_2023-08-05-10-08-05-67_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://github.com/Team-xManager/xManager/assets/12599497/1ae38ee1-6405-4d70-aa4e-70d71758791b)

. For Google assistant, i tried it myself and worked perfectly. Unless there is a specific command that doesn't work I can just ask it to play or do anything and it works.

**Comment by Hit4man47** [comment]
@GitStudying Bro which version are you using

**Comment by GitStudying** [comment]
> @GitStudying Bro which version are you using

The same as you as far as I see 5.0.

**Comment by Hit4man47** [comment]
@GitStudying hey the cloned setting was one turning it OFF and reinstalling it fixed the error.
Everything works fine now
