### ISSUE TITLE
Virustotal Scan shows this as trojan.

### ISSUE THREAD

**Issue by Yashsomalkar** [Team-xManager/xManager#407]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  
- Android Version:  
- ROM Version:  
- xManager Version:
```

### 📝 Description

one of the IPs involved in it has these relations : https://www.virustotal.com/gui/ip-address/108.177.119.113/relations

### 📸 Screenshots

![image](https://github.com/Team-xManager/xManager/assets/95977604/def76cf6-3ebf-4347-9186-1f9e40d7bd0e)

**Comment by xC3FFF0E** [comment]
We are already aware about this. All of the red flags are 'false positives' as the source code is already shown to the public. These red flags are due to signature, compiling, etc.

Also, the relations are somewhat 'nonsense' especially with Communicating Files and Files Referring (it doesn't make sense that we have an exe or pdf file/s communicating to).
