### ISSUE TITLE
Unhelpful documentation

### ISSUE THREAD

**Issue by Fabian42** [Team-xManager/xManager#474]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
-
```

### 📝 Description

I got a recommendation for this app and had to blindly trust that it actually does what it does. The [website](https://www.xmanagerapp.com/), this repository (apart from the issues) and even the app itself makes zero mentions of Spotify or other relevant aspects. Instead, there are very high-level meta-descriptions like "easy to use", "minimalistic UI", "upgrade/downgrade" etc. The word "Spotify" appears for the first time in the installation confirmation popup by Android. All documentation about this app manages to talk around the main point better than a politician. I would almost assume that this has some reason, that you want to avoid being found via Google or whatever, but there seems to be no problem with mentioning Spotify in GitHub issues. You should really write down ANYTHING about the actual purpose of the app!

**Comment by Fabian42** [comment]
BTW, is there any technical reason why this has to be an app instead of just a website with a download button for the modded Spotify app?

**Comment by loustact** [comment]
> BTW, is there any technical reason why this has to be an app instead of just a website with a download button for the modded Spotify app?

If they distribute modded Spotify clients, Spotify has grounds to DMCA this project. This is also done by other patching projects like ReVanced to not get claimed.

Also, with the mention of Spotify thing. They probably do that to be careful not to be involved in legal bazinga. Just as a precaution. And I guess thy don't want it to be too popular as they place in the boot up screen saying ”Don't Make Us Popular!" If they do, they would end up closing shop like what happened to Vanced because the popularity would attract the eyes of Spotify and a potential DMCA might be on the horizon.
